spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/template_db
    username: postgres
    password: postgres

logging:
  level:
    org.springframework.web: INFO
    com.template.mapper: INFO
    org.springframework.security: INFO
