ALTER TABLE file_uploads
    ADD COLUMN IF NOT EXISTS deleted BOOLEAN DEFAULT false,
    ADD COLUMN IF NOT EXISTS version INTEGER DEFAULT 0,
    ADD COLUMN IF NOT EXISTS updated_by VARCHAR(50),
    ADD COLUMN IF NOT EXISTS updated_date TIMESTAMP;
